version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: address_search_service:${ADDRESS_SEARCH_SERVICE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    labels:
      # Enables traefik for this container.
    - traefik.enable=true
    - traefik.http.routers.address_search_service.rule=Host(`${ADDRESS_SEARCH_SERVICE_TRAEFIK_HOST:-address_search_service.localhost}`)
    - traefik.http.routers.address_search_service.entrypoints=http
    - traefik.http.routers.address_search_service.service=address_search_service
    - traefik.http.services.address_search_service.loadbalancer.server.port=${ADDRESS_SEARCH_SERVICE_PORT:-8000}
    networks:
    - default
    - traefik-shared
    environment:
      ADDRESS_SEARCH_SERVICE_HOST: 0.0.0.0



networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
